Repository ostis-ai/scl-machine, pull requests merged in 2022-10, with the labels that each got.

#2 Feature/ostis inference
  scl/cxx/inferenceModule/CMakeLists.txt
  scl/cxx/inferenceModule/agent/DirectInferenceAgent.cpp
  scl/cxx/inferenceModule/agent/DirectInferenceAgent.hpp
  scl/cxx/inferenceModule/classifier/FormulaClassifier.cpp
  scl/cxx/inferenceModule/classifier/FormulaClassifier.hpp
  scl/cxx/inferenceModule/formulas/Formula.hpp
  scl/cxx/inferenceModule/generator/SolutionTreeGenerator.cpp
  scl/cxx/inferenceModule/keynodes/InferenceKeynodes.cpp
  scl/cxx/inferenceModule/keynodes/InferenceKeynodes.hpp
  scl/cxx/inferenceModule/logic/LogicExpression.cpp
  scl/cxx/inferenceModule/logic/LogicExpression.hpp
  scl/cxx/inferenceModule/manager/DirectInferenceManager.cpp
  scl/cxx/inferenceModule/manager/DirectInferenceManager.hpp
  scl/cxx/inferenceModule/manager/TemplateManager.cpp
  scl/cxx/inferenceModule/manager/TemplateManager.hpp
  scl/cxx/inferenceModule/searcher/TemplateSearcher.cpp
  scl/cxx/inferenceModule/searcher/TemplateSearcher.hpp
  scl/cxx/inferenceModule/specification/agent_direct_inference/content/.gitkeep
  scl/cxx/inferenceModule/specification/agent_direct_inference/desc_agent_direct_inference.md
  scl/cxx/inferenceModule/specification/agent_direct_inference/lib_component_agent_direct_inference.scs
  scl/cxx/inferenceModule/test/testStructures/LogicModule/inferenceLogicFalseComplexRuleTest.scs
  scl/cxx/inferenceModule/test/testStructures/LogicModule/inferenceLogicTrueComplexRuleTest.scs
  scl/cxx/inferenceModule/test/testStructures/LogicModule/inferenceTestEquivalences.scs
  scl/cxx/inferenceModule/test/testStructures/LogicModule/testSeveralNestedEquivalenceRulesOneTemplateToGenerate.scs
  scl/cxx/inferenceModule/test/tests.cmake
  scl/cxx/inferenceModule/test/units/TestLogicModule.cpp
  scl/cxx/inferenceModule/utils/ReplacementsUtils.cpp
  scl/cxx/inferenceModule/utils/ReplacementsUtils.hpp
Labels: 0.2.0

#11 [ci] Add pre-commit
  .pre-commit-config.yaml
Labels: ci

#10 [test] Update tests for logic module
  scl/cxx/inferenceModule/test/testStructures/LogicModule/emptyInputStructureLogicRule.scs
  scl/cxx/inferenceModule/test/testStructures/LogicModule/emptyRulesSetQueueTest.scs
  scl/cxx/inferenceModule/test/testStructures/LogicModule/emptyRulesSetTest.scs
  scl/cxx/inferenceModule/test/testStructures/LogicModule/invalidInputStructureLogicRule.scs
  scl/cxx/inferenceModule/test/testStructures/LogicModule/trueComplexRuleTest.scs
  scl/cxx/inferenceModule/test/testStructures/LogicModule/trueDoubleApplyRuleTest.scs
  scl/cxx/inferenceModule/test/testStructures/LogicModule/trueSimpleRuleTest.scs
  scl/cxx/inferenceModule/test/testStructures/ManagerModule/inferenceManagerRuleUsedTest.scs
  scl/cxx/inferenceModule/test/testStructures/ManagerModule/lr_concept_weather_request_message_1.scs
  scl/cxx/inferenceModule/test/units/TestLogicModule.cpp
  scl/cxx/inferenceModule/test/units/TestManagerModule.cpp
Labels: test

#12 [doc] Update documentation about new applyInference
  docs/images/direct_inference_input_4.png
  docs/images/input_structure.png
  docs/images/output_structure.png
  docs/main.pdf
  docs/main.tex
  docs/scl-machine.tex
Labels: documentation, 0.2.0

#9 Update docs
  docs/changelog.md
  docs/dev/codestyle.md
  docs/dev/git-workflow.md
  docs/dev/pr.md
  docs/index.md
  mkdocs.yml
Labels: documentation, 0.2.0

#13 [test] Separate logic module arguments test
  docs/changelog.md
  scl/cxx/inferenceModule/test/testStructures/LogicModule/emptyInputStructureLogicRule.scs
  scl/cxx/inferenceModule/test/testStructures/LogicModule/emptyRulesSetQueueTest.scs
  scl/cxx/inferenceModule/test/testStructures/LogicModule/invalidInputStructureLogicRule.scs
  scl/cxx/inferenceModule/test/testStructures/LogicModule/logicModuleArgumentsTest.scs
  scl/cxx/inferenceModule/test/units/TestLogicModule.cpp
  scl/cxx/inferenceModule/test/units/TestLogicModuleArguments.cpp
Labels: test
